from __future__ import annotations

INK = "#1A1A1A"
INK_SOFT = "#555555"
INK_FAINT = "#E6E6E6"
FIGURE_BG = "white"

ACCEPTED = "#117733"
ESTIMATOR_BIAS_BRACKETED = "#88CCEE"
REJECTED = "#CC6677"
PRECISION_ACCEPTED = "#332288"
PRECISION_WARN = "#DDCC77"
REGIME_NA = "#999999"

DMC_PRIMARY = "#0072B2"
DMC_DIAGNOSTIC = "#D55E00"
LDA_PREDICTION = INK
SEED_BAND = "#CCDDEE"
TRIANGULATED_BAND = "#FAE5C2"

DMC_MARKER = "o"
DIAGNOSTIC_MARKER = "x"

STATUS_COLORS = {
    "accepted": ACCEPTED,
    "warn": PRECISION_WARN,
    "rejected": REJECTED,
    "na": REGIME_NA,
}

ESTIMATOR_STATUS_LABELS = {
    "PURE_ESTIMATOR_ACCEPTED": "PURE",
    "ENERGY_ESTIMATOR_ACCEPTED": "MIXED ENERGY",
    "ESTIMATOR_BIAS_BRACKETED": "BIAS BRACKET",
    "ESTIMATOR_REJECTED": "REJECTED",
    "NOT_EVALUATED": "N/A",
}
