from __future__ import annotations

INK = "#1A1A1A"
INK_SOFT = "#555555"
INK_FAINT = "#E6E6E6"
PAPER_BG = "white"

METHODOLOGY_GO = "#117733"
METHODOLOGY_BIAS_BRACKETED = "#88CCEE"
METHODOLOGY_NO_GO = "#CC6677"
PRECISION_GO = "#332288"
PRECISION_WARN = "#DDCC77"
REGIME_NA = "#999999"

DMC_PRIMARY = "#0072B2"
DMC_DIAGNOSTIC = "#D55E00"
LDA_PREDICTION = INK
SEED_BAND = "#CCDDEE"
TRIANGULATED_BAND = "#FAE5C2"

DMC_MARKER = "o"
DIAGNOSTIC_MARKER = "x"

STATUS_COLORS = {
    "go": METHODOLOGY_GO,
    "warn": PRECISION_WARN,
    "no_go": METHODOLOGY_NO_GO,
    "na": REGIME_NA,
}

TIER_GLYPHS = {
    "METHODOLOGY_GO_VIA_PURE_PLATEAU": "PURE",
    "METHODOLOGY_GO_VIA_MIXED_COMMUTES": "MIXED=PURE",
    "METHODOLOGY_BIAS_BRACKETED": "BIAS-BRACKETED",
    "METHODOLOGY_NO_GO": "NO-GO",
    "REGIME_NOT_SUPPORTED": "N/A",
}
